module.exports = {
  apps: [
    {
      name: "bot-manager-backend",
      script: "dist/app.js",
      cwd: "/home/linuxuser/bot-manager/backend",
      watch: false,
      autorestart: true,
      max_restarts: 5,
      min_uptime: "10s",
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
        BACKEND_PORT: 3001,
        FRONTEND_PORT: 7260,
        BOT_PORT_START: 7261,
        BACKEND_HOST: "0.0.0.0",
        FRONTEND_HOST: "0.0.0.0",
        NEXT_PUBLIC_API_BASE_URL: "http://localhost:3001",
        FRONTEND_URL: "http://localhost:7260",
        BOT_CONFIG_PATH: "./config/bots.json",
        DEFAULT_BOT_HOST: "localhost",
        CHROME_PATH: "/snap/bin/chromium",
        LOG_LEVEL: "info",
        HEALTH_CHECK_ENABLED: "true",
        DEV_MODE: "false",
        VERBOSE_SPAWNING: "false"
      },
      error_file: "/home/linuxuser/bot-manager/logs/bot-manager-backend-error.log",
      out_file: "/home/linuxuser/bot-manager/logs/bot-manager-backend-out.log",
      log_file: "/home/linuxuser/bot-manager/logs/bot-manager-backend-combined.log",
      time: true,
    },
  ],
};
